### ISSUE TITLE
[PE-D] Missing arguments in documentation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#220]
![image.png](https://raw.githubusercontent.com/Journeyman1998/ped/master/files/5ff68638-5f9d-4bee-8be1-6ed1e6f5c2fe.png)

Examples are correct

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Journeyman1998/ped#2

**Comment by DmitriYam** [comment]
dunzo
