### ISSUE TITLE
[PE-D] Minimum weightage not correct

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#223]
![image.png](https://raw.githubusercontent.com/Journeyman1998/ped/master/files/6e014189-7d71-4cf5-95b2-af63df213563.png)

![image.png](https://raw.githubusercontent.com/Journeyman1998/ped/master/files/7192ee1d-67a6-4945-a14f-1c264d06903e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Journeyman1998/ped#3

**Comment by jiexiong-zeng** [comment]
change the ug to match

**Comment by DmitriYam** [comment]
dunzo
