### ISSUE TITLE
[PE-D] Possible bug in addgrade and CAP

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#231]
![image.png](https://raw.githubusercontent.com/arvejw/ped/main/files/f75d0348-541d-48f3-af67-ce629f7f4ad6.png)

To contextualize, I only have one module, CS2113T, in the semester. After adding the grade A, calling `cap` gives a CAP of `5.0` which is correct since I only have 1 module.

Here are the command calls:
1. `/m CS2113T addgrade A`
2. `cap`

![image.png](https://raw.githubusercontent.com/arvejw/ped/main/files/c083fe7c-6b15-47ac-b105-adfc5998f39b.png)

Next I add a new grade which is in an incorrect format `!@#`, which still successfully replaces the old grade. However when calling `cap` again the CAP shown is still the old value of `5.0`. Not sure if this is intended or it should be reflected as invalid now since an invalid grade was entered.

Here are the command calls:
1. `/m CS2113T addgrade !@#`
2. `cap`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: arvejw/ped#4

**Comment by DmitriYam** [comment]
dunzo
