### ISSUE TITLE
[PE-D] Command is case-sensitive should be mentioned

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#235]
![image.png](https://raw.githubusercontent.com/Xuefei2001/ped/main/files/df05b80b-149b-4043-9c0c-4a8658801fef.png)
"HELP" is considered an invalid command, if the command format is strictly case-sensitive, it should be mentioned in UG or greeting message. Also, it may be better to allow both lower and upper case for better user experience.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Xuefei2001/ped#4

**Comment by DmitriYam** [comment]
dunzo
