### ISSUE TITLE
[PE-D] Cannot recognize the module

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#237]
![Screen Shot 2021-10-29 at 5.12.08 PM.png](https://raw.githubusercontent.com/Vincent6896/ped/main/files/0bf0e0e8-d75f-4a3f-a59b-2189194af45a.png)
It cannot recognize the module name even users input the correct name and its description

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Vincent6896/ped#4

**Comment by jiexiong-zeng** [comment]
No feedback for addclass

**Comment by yapjoonsiong** [comment]
can someone pls try to recreate this bug because i cant
