### ISSUE TITLE
[PE-D] Contrast in format of list commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#244]
![image.png](https://raw.githubusercontent.com/Xuefei2001/ped/main/files/e5418b90-411c-4755-8b35-ab1e4f927cca.png)
The instruction given when a wrong command is detected should be the same as the format in help message, otherwise it can be confusing which to follow.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Xuefei2001/ped#5

**Comment by jiexiong-zeng** [comment]
update help in Ui
