### ISSUE TITLE
[PE-D] Switch semester default setting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#251]
What is the default setting for semester? Is it necessary to switch to a semester before I add/delete and so on? This confuses me as it is not mentioned anywhere and the program seems to function without switching to any semester first. If it is possible to allow user to check current semester he/she is in it would be better to include this feature.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Xuefei2001/ped#6

**Comment by jiexiong-zeng** [comment]
print feedback on semester when entering nocap
