### ISSUE TITLE
[PE-D] Ambiguity in listing of tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-1/tp#263]
![image.png](https://raw.githubusercontent.com/arvejw/ped/main/files/5c228c72-aa81-4c31-9147-6cbca257fb76.png)

Not sure if this is a matter of implementation but it is vague if gradable tasks are considered tasks as well

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: arvejw/ped#8

**Comment by naijie2108** [comment]
Explained in ug, and also added list gradable and list normal methods, but unsure if we should add a module list gradable task function to make things clearer
